# Generated by Django 5.2 on 2025-06-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='registrointentologin',
            name='email_ingresado',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registrointentologin',
            name='exitoso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrointentologin',
            name='user_agent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registrointentologin',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_login', to='api_sistema.usuario'),
        ),
        migrations.AlterField(
            model_name='tokenrecuperacion',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to='api_sistema.rol'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to='api_sistema.usuario'),
        ),
    ]
