# Generated by Django 5.2 on 2025-06-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sistema', '0002_alter_usuario_managers_remove_estacion_latitud_and_more'),
        ('api_sistema', '0002_cleanup_and_remove_coordinates'),
    ]

    operations = [
    ]
